
# Connection to the MySQL database

Database:
  Address: '195.3.220.103'
  Port: '3306'
  Database: 'practice_code'
  Username: 'lorendel_learning'
  Password: 'lorendel_13'

# You can use commands and placeholder: %player%

promo-rewards:
  - 'give %player% diamond 64'



