
# Connection to the MySQL database

Database:
  Address: 'ip'
  Port: 'port'
  Database: 'database_name'
  Username: 'database_username'
  Password: 'database_password'

# You can use commands and placeholder: %player%

promo-rewards:
  - 'give %player% diamond 64'



