name: NanoPromocode
version: '${project.version}'
main: me.lorendel.nanopromocode.NanoPromocode
api-version: '1.20'
commands:
  promo:
    description: Command to use a promo code!
    usage: </command>
