
# Connection to the MySQL database

Database:
  Address: '127.0.0.1'
  Port: '3306'
  Database: 'database_name'
  Username: 'database_username'
  Password: 'database_password'

# You can use commands and placeholder: %player%

promo-rewards:
  - 'give %player% diamond 64'



