name: NanoPromocode
version: '1.3-SNAPSHOT'
main: me.lorendel.nanopromocode.NanoPromocode
api-version: '1.20'
commands:
  promo:
    description: Command to interact with promo plugin!
    usage: </command>
